"""
Binary I/O utilities for reading/writing solver files.
"""

import numpy as np


def read_density_field(nelx: int, nely: int, nelz: int, filename: str) -> np.ndarray:
    """
    Read binary density field generated by C solver.
    
    Args:
        nelx, nely, nelz: Number of elements in each direction
        filename: Path to binary density file
    
    Returns:
        numpy array: Density field shaped (nelx, nely, nelz)
    """
    expected_size = nelx * nely * nelz
    
    # Read binary file
    density_flat = np.fromfile(filename, dtype=np.float64)
    
    if density_flat.size != expected_size:
        raise ValueError(
            f"Density file size mismatch. Expected {expected_size} values, "
            f"got {density_flat.size}"
        )
    
    # Reshape to match C indexing: i1 * nely * nelz + k1 * nely + j1
    # This gives us (nelx, nelz, nely) in C order
    density = density_flat.reshape((nelx, nelz, nely))
    
    # Transpose to standard (nelx, nely, nelz) format
    density = np.transpose(density, (0, 2, 1))
    
    return density.astype(np.float32)
